// import "./js/task7.js"
import "./js/task8.js"
// import "./js/task9.js"
// import "./js/task10.js"
// import "./js/task11.js"
// import "./js/task12.js"
// import "./js/task13.js"
// import "./js/task14.js"
// import "./js/task15.js"